[package]
name = "lets-meet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geocoding = { version = "0.4.0", features = ["rustls-tls"] }
serde_yaml = "0.9.14"
versor = "0.1.0"
